apiVersion: v2
name: httpd-git-chart
description: A Helm chart for deploying the httpd image that auto-updates website content from a git repo
type: application
version: 1.0.3
appVersion: "2.4.66-trixie"
