image:
  repository: starwitorg/httpd-git
  tag: 2.4.66
  pullPolicy: IfNotPresent

replicaCount: 1

# Repo and branch used by the container's update script
repoUrl: https://codeberg.org/ztarbug/gtp-landingpage.git
# if set it will be used to clone code from private repos
accessToken: ""
branch: main
cronSchedule: "*/5 * * * *"

# URL replacement settings
baseUrl: ""
placeholder: "{{BASE_URL}}"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: landing.cluster.local
      paths:
        - path: /
          pathType: Prefix

  annotations: {}
  # tls:
  #   - secretName: landing.cluster.local
  #     hosts:
  #       - landing.cluster.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
